common/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.ProductList.as_view()),
	path('<int:pk>', views.ProductDetail.as_view())
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
]

common/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
	title = models.CharField(max_length=30)
	description = models.TextField()
	target_amount = models.IntegerField()
	end_date = models.DateField()
	amount_per_time = models.IntegerField()

	def __str__(self):
		return f'[{self.pk}]{self.title}'

common/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product

# Create your views here.

class ProductList(ListView):
	model = Product
	template_name = 'common/index.html'

class ProductDetail(DetailView):
	model = Product
	template_name = 'common/detail.html'

templates/common/detail.html
<h1> {{ product.title }}</h1>
<div>

	{{product.description}}
	{{product.target_amount }}
	{{product.end_date}}
</div>

templates/common/index.html
{% if product_list %}
	<ul>
		{% for product in product_list %}
		<li>
			<a href="/common/{{product.id }}">{{ product.title }} </a> : {{ product.description }}
		</li>
		{% endfor %}
	</ul>
{% endif %}

templates/common/product_create.html
<h1>hi</h1>

templates/common/product_detail.html
<h1> {{ product.title }}</h1>
	<div> 설명  : {{product.description}}</div>
	<div>목표 가격 :{{product.target_amount }}</div>
	<div>종료 일자 :{{product.end_date}}</div>

<a href="/common/update/{{product.id}}">수정하기</a>

templates/common/product_list.html
{% if product_list %}
<ul>
	{% for product in product_list %}
	<li>
		<a href="/common/{{product.id }}">{{ product.title }} </a> : {{ product.description }}
	</li>
	{% endfor %}
</ul>
{% endif %}

templates/common/product_update.html
<h1>
	product_update
</h1>